apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: afb208j3d-go
  janus-idp.io/tekton: afb208j3d-go
  backstage.io/kubernetes-id: afb208j3d-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: afb208j3d-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
